### ISSUE TITLE
get rid of HTML tags in modals

### ISSUE THREAD

**Issue by hejanew** [shilpamagrawal15/cookingmamas#24]
@shilpamagrawal15 @apsoleimany 
I wanted to bold the important parts of the objectives as suggested through user testing, but the HTML bold tags show up in the modal. Anyone know how to fix this?

![screen shot 2015-05-13 at 2 38 08 pm](https://cloud.githubusercontent.com/assets/12088752/7618112/ddf6265c-f97d-11e4-93a3-7f2c6347c0e2.png)

**Comment by shilpamagrawal15** [comment]
assigned to @apsoleimany since she's going to look into modal text for line break stuff

**Comment by hejanew** [comment]
![level4](https://cloud.githubusercontent.com/assets/12088752/7619597/d39d0c7a-f987-11e4-9a64-d1e6c194e4e7.png)

Top right cost box would update each time the user pressed BUY on the shopping list.

Potential revenue boxes would update whenever the user entered a number for (Serves #) in the corresponding recipe

**Comment by shilpamagrawal15** [comment]
@hejanew  did you mean to put this image on issue #26 ?
