### ISSUE TITLE
what should the user be doing on level 4

### ISSUE THREAD

**Issue by shilpamagrawal15** [shilpamagrawal15/cookingmamas#26]
@apsoleimany @hejanew 

I am confused about what the user should be inputting on level 4. right now i have a working real-time store (as jane suggested) where they can purchase items in real time. i can get access to how much they will have spent in the store, and it will update the cabinet in realtime. right now it looks like this

![image](https://cloud.githubusercontent.com/assets/5384737/7619336/f85301b6-f985-11e4-9bcb-90dd22da92c5.png)

QUESTIONS:
- where should the amount they spent in the store be shown
- how should users indicate how much profit they are going to get from a choice?
- how do they choose their choice - for the option that they do not go with, do they have to input 0 in all of the input boxes?

if you have a clear sense, it would be helpful if you could do a quick sketch of what exactly they should be inputting (should they just be choosing between option A & B instead of inputting values)? help please!!

**Comment by avaamini** [comment]
1) you can display the amount spent in the store on the right side of that bottom panel. 
2&3) I guess the answer to this is dependent upon how they choose their choice/what they need to be inputting. I'm still not totally clear on what's intended. If they just choose between option A&B, we can have them input the profit, but not the amounts of each dish/ingredients.... My thoughts are kind of scattered and I'm not sure what the "ideal" is. Here is an idea:
- they input dish servings and ingredient amounts as usual. 
- on the bottom panel, after they see how much they spent in the store, they'll also have to input the profit. 
- we then process these inputs and give feedback *
- if they try to cook both Lemon Bars and Coconut Shrimp, they're wrong and get one kind of feedback message.
- if they try to cook only Coconut Shrimp, then they get another type of feedback messages (of course these can be more specific given what exact mistakes they made)
- they cook only Lemon Bars. 
  --> then, if they didn't purchase anything from the store (i.e, they did some recalculation and realized Lemon Bars were the way to go), and they satisfy the request, they get the "Great job!" message. 
  --> if they purchased stuff but then cooked Lemon Bars, we give them another message, saying that they wasted money in the store and didn't maximize the profit (or whatever)

of course in all these cases we'd still check for correct proportions, right number of servings. 

thoughts?

**Comment by shilpamagrawal15** [comment]
@apsoleimany 

this is what Jane suggested. do you agree with it? it is largely in-line with what you outlined:

![image](https://cloud.githubusercontent.com/assets/5384737/7622010/3e87a908-f999-11e4-8f01-44ab92c26683.png)

I'll work on getting those sections up tonight after SK formal (~11pm), but if you agree with this representation, you can move forward with doing feedback for the object that would come out of these inputs. let me know on ultimately what you decide!

**Comment by shilpamagrawal15** [comment]
@hejanew - the one thing that I think is different is maybe they have to input the potential revenue (more proportions math!) rather than see it appear based on the # of servings they input. thoughts?
