### ISSUE TITLE
Cabinet doesn't update correctly when player uses "tab" to get from one input textbox to the next

### ISSUE THREAD

**Issue by hejanew** [shilpamagrawal15/cookingmamas#4]
If you use tab to get from one input textbook to the next, weird stuff happens. When you get to a recipe that uses an ingredient that you already used previously - let's call it ing_prev_used, when you finish typing the input value of the ingredient in the line directly above ing_prev_used and press tab the amount of of ing_prev_used in the cabinet goes back to the original starting amount. Will probably be easier to go over this bug in person. Easy fix would just be to tell people they can't tab between input boxes

**Comment by shilpamagrawal15** [comment]
@hejanew  - I have identified the bug and I know why it is happening. I have to think about how to fix it - the logic for updating the cabinet is a bit more complicated than I had hoped it would be :(

**Comment by shilpamagrawal15** [comment]
@hejanew  - i just pushed code. can you let me know if it works / if it caused additional bugs?

**Comment by shilpamagrawal15** [comment]
@hejanew - just pushed new code again. let me know if it works, and close the issue if it does!
