### ISSUE TITLE
Decide on Color Scheme for the game

### ISSUE THREAD

**Issue by shilpamagrawal15** [shilpamagrawal15/cookingmamas#7]
@hejanew - based on the user testing feedback, can you decide on a color and looks scheme that you would like for the game? e.g. what color should the background be, what colors should the recipes be, etc. then i will quickly plug it into the code!

**Comment by shilpamagrawal15** [comment]
@hejanew - thanks for creating this! do you mind updating this from RGB to HEX? Also, can you specify what "Your Store" and "Your Shopping List" should look like in Level 4?

![color_layout](https://cloud.githubusercontent.com/assets/5384737/7596957/ad047ee6-f8be-11e4-838b-25fde21699c1.png)

**Comment by hejanew** [comment]
@shilpamagrawal15 
Choose Level and Cook: #A230A8
Objective: #EA696D
Cabinet: #C17230
Orig Recipe: #7BEF7E
New Recipe: #30BEA3
Store: #8FBC8F
Shopping List: #F5F5F5

**Comment by shilpamagrawal15** [comment]
@hejanew  - do you want to input these colors, or would you like me to? either way is fine - will assign accordingly

**Comment by hejanew** [comment]
I can do the background, but I am unsure about how to do the bootstrap elements

**Comment by shilpamagrawal15** [comment]
Which are the bootstrap elements?

Actually I'll input the colors to avoid merge conflicts since I'll be working on code in the same location -- don't worry about it!

**Comment by hejanew** [comment]
@shilpamagrawal15 
Changed the background to cork, but idk how to change the color of the boxes that were formatted through bootstrap. For example, when I try to change the background color of the Objective box, nothing happens 
![screen shot 2015-05-14 at 12 10 07 am](https://cloud.githubusercontent.com/assets/12088752/7625976/b0966a82-f9cd-11e4-9538-a213ea7e8f30.png)

**Comment by shilpamagrawal15** [comment]
@hejanew - use background, not background-color. I'll change them!

**Comment by shilpamagrawal15** [comment]
@hejanew  - just pushed color scheme. pull and see what you think. if you want to change any of the colors, you can do that within style.css
