### ISSUE TITLE
Update the levels object for level 4

### ISSUE THREAD

**Issue by shilpamagrawal15** [shilpamagrawal15/cookingmamas#8]
Let me know when you have pushed this! Thanks

**Comment by hejanew** [comment]
Pushed. Added images for the new ingredients and updated the ingredients objects to add the new ingredients as well. Notice that for the items at the store, the way Kara had it set up was that items couldn't be purchased by unit (e.g. to get 2 eggs, you have to buy the 1/2 dozen pack), so for the objects at the stores, they have attributes "cost_per_unit" and "amount_per_unit". If this will make things too complicated, we can adjust the prices and the amount each client pays per person
