### ISSUE TITLE
More detailed feedback for Level 1

### ISSUE THREAD

**Issue by hejanew** [shilpamagrawal15/cookingmamas#9]
@shilpamagrawal15 @apsoleimany 
Because we are focusing on Level 4 and it has been determined that it will be too tricky to give real-time feedback when the proportions within one recipe are not consistent, we just need to give more detailed modal feedback in Level 1, similar to how it is done in Level 2.

**Comment by shilpamagrawal15** [comment]
@hejanew - who is the point person on coming up with this feedback?

**Comment by avaamini** [comment]
@hejanew the same type of feedback given in Level 2? Or even more specific?

**Comment by avaamini** [comment]
@hejanew @shilpamagrawal15 now the same feedback is given in Level 1 and Level 2

**Comment by shilpamagrawal15** [comment]
@hejanew - can you take a look and see if this satisfies what you were thinking?

**Comment by hejanew** [comment]
@apsoleimany 
it told me I was correct when I had incorrect proportions for the PB cookies
![screen shot 2015-05-13 at 12 59 11 am](https://cloud.githubusercontent.com/assets/12088752/7604068/57ec8f28-f90b-11e4-8741-657ee13bbd74.png)

**Comment by hejanew** [comment]
@apsoleimany 
actually not just PB cookies. If I have the wrong proportions on any recipe, it still tells me I am correct

**Comment by shilpamagrawal15** [comment]
@hejanew  - this is because I changed the data representation for recipes, so Ava has to update the feedback code to accomodate this new data representation

**Comment by hejanew** [comment]
@apsoleimany 
In Levels 1 and 3, when I submit incorrect proportions of ingredients, the modal informs me that I used the right ingredient amounts

In level 2, pressing the Cook button makes the Objective modal pop up instead of the feedback modal

**Comment by apsoleimany** [comment]
@hejanew should be fixed let me know if not

**Comment by avaamini** [comment]
@hejanew should be fixed let me know if not
